sudo: false
language: perl
perl:
- '5.30'
- '5.14'
before_install:
- git config --global user.name "TravisCI"
install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla
- cpanm --quiet --notest Test::Kwalitee
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest Dist::Zilla::App::Command::cover
- dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
- dzil listdeps --author | cpanm --skip-satisfied
- export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c
  HARNESS_TIMER=1
- dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet --notest --skip-satisfied
script:
- dzil smoke --release --author
after_success:
- dzil cover -outputdir cover_db -report coveralls
notifications:
  slack:
    secure: C3pbifOT8+F8muQmTRzDZE+N1Wof6HxCt6ppIh1HStmJF1UsdLZDWesjbZ9Zu7zDa+DaYTyFphP15JHutfSfMKtWRFw0Pb2c35i940886wiujYREl+Latu+vEmgjUR8bRJ0A0IKvmT/upjz2b/nLcDobBHC4rTZVip4vhzaJ1iw=
