name: Continuous Integration
on:
  push:
  schedule:
    - cron: '0 0 */28 */1 *'

env:
  GMP_HOME: /usr
  MPFR_HOME: /usr

jobs:
  linux:
    runs-on: ubuntu-latest
    name: "Continuous Integration"
    steps:
      - name: "Install C libraries for dependencies"
        run: sudo apt-get update && sudo apt-get install -y libmpfr-dev libgmp-dev
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: uses install-with-cpanm
        uses: perl-actions/install-with-cpanm@10d60f00b4073f484fc29d45bfbe2f776397ab3d # v1.7
        with:
          cpanfile: "cpanfile"
          sudo: true
      - run: perl Makefile.PL
      - run: make test
