name: Dist::Zilla Action
on:
  push:
  schedule:
    - cron: '0 0 */28 */1 *'

env:
  GMP_HOME: /usr
  MPFR_HOME: /usr

jobs:
  linux:
    runs-on: ubuntu-latest
    name: "dzil run"

    steps:
      - name: "Install C libraries for dependencies"
        run: sudo apt-get update && sudo apt-get install -y libmpfr-dev libgmp-dev
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Installing dependencies and testing all using dzil"
        uses: jonasbn/github-action-perl-dist-zilla@0.3.0
        with:
          dzil-arguments: 'test --all'
